### ISSUE TITLE
ios13闪退

### ISSUE THREAD

**Issue by TotoroOnTheTree** [baacloud/url#38]
ios13没办法使用呢，一直闪退，备用方式也没用。

**Comment by bbrcloud** [comment]
彻底删除之前的软件后，用testfight安装

**Comment by TotoroOnTheTree** [comment]
备用方法也不行。提示必须年满13岁。
我先下载的testflight，然后退出登陆给的文档的appid，之后打开testflight就是这个提示。

**Comment by bbrcloud** [comment]
请不要登录使用我们的账户进行安装，退出我们的账户用你自己的账户安装。

**Comment by TotoroOnTheTree** [comment]
用自己的账号打开testflight，显示的是没有可用的测试。

**Comment by TotoroOnTheTree** [comment]
是我的操作方式不对，找到原因了。谢谢
