### ISSUE TITLE
你好，请问2021年还有学者计划或者教育优惠吗

### ISSUE THREAD

**Issue by ZP-Guo** [baacloud/url#66]
如题，请问还有学者计划或者教育优惠的套餐吗，学生党表示想争取一下。我已经用你们家的VPN一年多了，觉得挺好的，价格优惠，速度还行，流量也大。就是想知道还会像去年那样搞活动不，打个折啥的。像2019年那样全免的就算了，你们维护这个也不容易，我觉得能像去年那样打个折就ok了。

**Comment by bbrcloud** [comment]
今年的活动已经在10月24日结束了的，明年的敬请关注我们的推特与电报频道。

**Comment by ZP-Guo** [comment]
> 今年的活动已经在10月24日结束了的，明年的敬请关注我们的推特与电报频道。

好的非常感谢。
